import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {DatabaseService} from "@/lib/DatabaseService";
import AppDataSource from "@/data-source";
import {connection} from "next/server";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    // await DatabaseService.getInstance();
    console.log("AAAAAAAAAAAAAAAAAA");
    console.log(process.env.SUPABASE_SSL_CERT_RAW);
    console.log(process.env.SUPABASE_DB_HOST);
    console.log(process.env.SUPABASE_DB_PORT);
    console.log(process.env.SUPABASE_DB_USER);
    console.log(process.env.SUPABASE_DB_PASSWORD);
    console.log(process.env.SUPABASE_DB_NAME);

    const connection = await AppDataSource.initialize();
    console.log('isInitialized: ', connection.isInitialized);
    return (
        <html lang="en">
        <body className={inter.className}>{children}</body>
        </html>
    );
}
