import type {Metadata} from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {

    console.log('HYPERDRIVE:', JSON.stringify(process.env.HYPERDRIVE));

    return (
        <html lang="en">
        <body>{children}</body>
        </html>
    );
}
